In [1]:
#Numpy의 기초

import numpy as np

#Numpy 배열 생성 --- 여러 값이 나열된 것

#python의 리스트로부터 numpy배열을 만든다
a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [3]:
#2중 리스트로부터 Numpy의 2차원 배열을 만든다
import numpy as np

b = np.array([[0,1,2,3,4],
              [5,6,7,8,9]])
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
#3중 리스트로부터 Numpy의 3차원 배열을 만든다

c = np.array([[[0,1,2],[3,4,5]],
              [[6,7,8],[9,10,11]]])
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [8]:
#Numpy 배열은 다른 함수를 사용해서도 생성할 수 있음
#zeros(), ones(), arange()

import numpy as np
d = np.zeros(8) #0이 8개 저장된 배열
print(d)

e = np.ones(8) #1이 8개 저장된 배열
print(e)

f = np.arange(8) #0부터 7까지 저장된 배열 = 반 열린구간 default:0
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [9]:
#배열의 형태 --- shape() 함수로 조사 가능, 반환형태: 튜플

import numpy as np

a = np.array([[0,1,2],
              [3,4,5]]) # 2x3의 2차원 배열
print(np.shape(a)) # a의 형태를 표시, 결과 = (행 수, 열 수)를 나타내는 튜플

(2, 3)


In [13]:
# 배열의 가장 바깥쪽의 요소, 즉 행 수를 구하는 경우 len()함수 사용

print(len(a))

2


In [14]:
#배열과 수치 간에 연산

import numpy as np

a = np.array([[0,1,2],
             [3,4,5]]) #2차원 배열

print(a)
print()
print(a+3) #각 요소에 3을 더한다
print()
print(a*3) #각 요소에 3을 곱한다

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [15]:
#배열끼리의 연산

b = np.array([[0,1,2],
            [3,4,5]]) #2차원 배열

c = np.array([[2,0,1],
            [5,3,4]]) #2차원 배열

print(b)
print()
print(c)
print()
print(b+c)
print()
print(b*c)
print()

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]



In [21]:
#배열의 각 요소로 접근하기 위해서는?  인덱스 사용

import numpy as np

a = np.array([1,2,3,4,5])
print(a[3]) #인덱스 지정

4


In [22]:
#인덱스를 통해 요소 바꿀 수 있음

a[2] = 9
print(a) # 3이 있던 자리에 9가 들어감

[1 2 9 4 5]


In [25]:
#2차원 배열의 요소로 접근하는 방법

b = np.array([[0,1,2],
            [3,4,5]])

print(b[1,2]) #b[1][2]  --- 코드에서 배열은 인덱스 상 0번째행/열에서 시작하기 때문에 행렬 b의 1행 2열을 나타냄

5


In [26]:
#2차원 배열의 요소를 변경할 경우

b[1, 2] = 9 #5의 값을 9로 바꿈

print(b) 

[[0 1 2]
 [3 4 9]]


In [34]:
#행/열에 접근하는 방법
c = np.array([[0,1,2],
              [3,4,5]])

print(c[1, :]) #인덱스가 1인 행을 취득

print()

c[:, 1] = np.array([6,7]) #인덱스가 1인 열을 교체
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


In [35]:
#함수의 인수, 반환값으로서의 배열

import numpy as np

def my_func(x):
    y = x * 2 + 1
    return y

a = np.array([[0,1,2],
              [3,4,5]]) #2차원 배열
b = my_func(a) #인수로서 배열을 전달, 반환값으로서 배열을 전달

print(b)

[[ 1  3  5]
 [ 7  9 11]]


In [36]:
#Numpy의 여러가지 기능
#sum(), average(), max(), min()

import numpy as np

a = np.array([[0,1,2],
             [3,4,5]]) #2차원 배열

print("합계: ", np.sum(a))
print("평균: ", np.average(a))
print("최댓값: ", np.max(a))
print("최솟값: ", np.min(a))

합계:  15
평균:  2.5
최댓값:  5
최솟값:  0


In [40]:
#내가 만들어본 문제
#역함수 존재 여부 확인 함수 만들어보기
import numpy as np

a = np.array([[0,1],
            [3,4]])

b = np. array([[10,10],
             [10,10]])

def inv_func(x):
    a=x[0,0]
    d=x[1,1]
    b=x[0,1]
    c=x[1,0]
    
    if((a*d)-(b*c)!=0):
        print(x,"는 역함수가 존재한다")
    else:
        print(x,"는 역함수가 존재하지 않는다")
    
inv_func(a)
inv_func(b)

[[0 1]
 [3 4]] 는 역함수가 존재한다
[[10 10]
 [10 10]] 는 역함수가 존재하지 않는다


In [42]:
#2차원 배열을 두 개 기술하고, 서로의 합, 차, 곱 구하기

import numpy as np

a = np.array([[0,1,2],
              [3,4,5]])
b = np.array([[5,4,3],
            [2,1,0]])

print()
print(a+b)

print()
print(a-b)

print()
print(a*b)


[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]

[[0 4 6]
 [6 4 0]]
