In [2]:
#여러개의 데이터를 하나로 묶어 다루는 방법 --- 스칼라, 벡터, 행렬, 텐서

#스칼라의 예
a=1
b=1.2
c= -0.25
d= 1.2e5  #1.2*(10의 5제곱)=120000


In [4]:
#벡터의 구현
#벡터는 스칼라를 직선상에 나열한 것
#세로로 수치를 나열하는 '세로벡터', 가로로 수치를 나열하는 '가로벡터'

#벡터를 NumPy의 1차원 배열로 나타낸다
import numpy as np

a = np.array([1,2,3]) #1차원 배열로 벡터를 나타낸다
print(a)

b = np.array([-2.4, 0.25, -1.3, 1.8, 0.61])
print(b)

[1 2 3]
[-2.4   0.25 -1.3   1.8   0.61]


In [6]:
#행렬 : 스칼라를 격자형태로 나열한 것
#행렬을 Numpy의 2차원 배열로 나타낸다
import numpy as np

a = np.array([[1,2,3],[4,5,6]]) # 2*3의 행렬
print(a)

b = np.array([[0.21, 0.14],[-1.3, 0.81],[0.12, -2.1]]) # 3*2의 행렬
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


In [8]:
#텐서 : 스칼라를 여러 개의 차원으로 나열한 것 (스칼라, 벡터, 행렬을 포함함)
#3층의 텐서를 NumPy의 배열로 나타낸다

a = np.array([[[0,1,2,3],
               [2,3,4,5],
               [4,5,6,7]],
              [[1,2,3,4],
               [3,4,5,6],
               [5,6,7,8]]])
print(a) #행렬이 2개 나열되어있음 --- 3차원 텐서

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


In [11]:
import numpy as np

#스칼라
a = 1.5
print(a)

print()

#벡터
b = np.array([1,2,3,4,5])
print(b)
print()

#행렬
c = np.array([[1,2,3],[4,5,6]])
print(c)
print()

#텐서
d = np.array([[[1,2,3,4],[3,4,5,6]],[[5,6,7,8],[7,8,9,10]]])
print(d)

1.5

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3  4]
  [ 3  4  5  6]]

 [[ 5  6  7  8]
  [ 7  8  9 10]]]


In [12]:
#벡터의 내적과 놈
#내적 : 벡터끼리의 곱의 한 종류. 
#벡터a와 벡터b가 내적하려면 두 개의 벡터 요소 수가 같아야 함
#벡터의 내적 계산
import numpy as np

a = np.array([1,2,3])
b = np.array([3,2,1])

print("--- dot()함수 ---")
print(np.dot(a,b)) # dot() 함수에 의한 내적
print("--- 곱의 총합 ---")
print(np.sum(a*b)) #곱의 총합에 의한 내적

#두 계산결과는 모두 같은 결과. 
#내적은 두 개의 벡터의 상관관계를 구할 때 등에 사용됨.

--- dot()함수 ---
10
--- 곱의 총합 ---
10


In [13]:
#놈 : 벡터의 크기를 나타내는 양. 
#L2놈 : 벡터의 각 요소를 제곱합하여 제곱근을 구해 계싼
#L1놈 : 벡터의 각 요소의 절댓값을 더해서 계산
#일반화된 놈 : 벡터의 각 요소에 p제곱한 것을 더해 전체 1/p 제곱하여 계산

#놈의 계산 --- linalg.norm()함수 사용
import numpy as np

a = np.array([1,1,-1,-1])

print("--- L2놈 ---")
print(np.linalg.norm(a)) # L2놈(디폴트)

print("--- L1놈 ---")
print(np.linalg.norm(a,1)) # L1놈

#놈의 종류에 따라 벡터의 크기는 다른 값이 됨.
#놈은 인공지능에서 정칙화에 쓰임. '정칙화'란 필요 이상으로 네트워크 학습이 진행되는 것을 파라미터를 조절해서 예방하는 것.

--- L2놈 ---
2.0
--- L1놈 ---
4.0


In [15]:
#Question. 벡터a와 벡터b의 내적, 벡터a와 L2놈과 L1놈 구하기
import numpy as np

a = np.array([1,-2,2])
b = np.array([2,-2,1])

print("--- 내적 ---")
print(np.dot(a,b))

print("--- L2놈 ---")
print(np.linalg.norm(a))

print("--- L1놈 ---")
print(np.linalg.norm(a,1))



--- 내적 ---
8
--- L2놈 ---
3.0
--- L1놈 ---
5.0


In [17]:
#행렬의 곱
#벡터끼리의 내적을 행렬로 확장하면 행렬의 곱이 됨
#행렬의 곱은 인공지능에서 효율적인 계산을 시행하기 위해서 중요한 조작임

import numpy as np

a = np.array([[0,1,2],
              [1,2,3]])
b = np.array([[2,1],
              [2,1],
              [2,1]])

print(np.dot(a,b))

[[ 6  3]
 [12  6]]


In [19]:
#행렬의 요소별 곱(아다마르 곱) --- a11,b11 요소끼리 단순히 곱한 결과를 요소로 둠
#NumPy를 사용해 요소별 곱을 계산

import numpy as np

a = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])

b = np.array([[0,1,2],
            [2,0,1],
            [1,2,0]])

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [23]:
#Question 행렬a와 행렬b의 행렬곱, 행렬 c와 행렬d의 요소별 곱

import numpy as np
a = np.array([[0,1,2],
              [1,2,3]])
b = np.array([[0,1],
              [1,2],
              [2,3]])

#행렬곱
c = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])

d = np.array([[0,2,0],
              [2,0,2],
              [0,2,0]])

#행렬별 곱
print("---행렬 a와 행렬 b의 행렬곱")
print(np.dot(a,b))
print()
print("---행렬 c와 행렬 d의 요소별 곱")
print(c*d)

---행렬 a와 행렬 b의 행렬곱
[[ 5  8]
 [ 8 14]]

---행렬 c와 행렬 d의 요소별 곱
[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]


In [24]:
#전치 : 행과 열을 바꿈. 인공지능의 코드에서는 전치를 자주 사용함
#행렬을 전치함으로써 행과 열이 바뀜
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = a.T

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [25]:
#행렬곱을 할 수 없는 상황에서 전치를 하면 행렬곱이 가능해질 수도 있다.
#전치하고 나서 행렬곱 실시

import numpy as np

a = np.array([[0,1,2],
              [1,2,3]]) #2*3의 행렬
b = np.array([[0,1,2],
              [1,2,3]]) #2*3의 행렬 이대로는 행렬곱을 할 수 없다

#print(np.dot(a,b)) #전치하지 않고 행렬곱을 취하면 에러
print(np.dot(a,b.T)) #전치에 의해 행렬곱이 가능해짐

[[ 5  8]
 [ 8 14]]


In [27]:
#Question 행렬a 또는 행렬b를 전치하고, 행렬a와 행렬b의 행렬곱을 계산한다

import numpy as np
a = np.array([[0,1,2],
              [1,2,3]])
b = np.array([[0,1,2],
             [2,3,4]])

#행렬곱
print(np.dot(a,b.T))

[[ 5 11]
 [ 8 20]]


In [31]:
#행렬식을 사용합으로써 역행렬을 구할 수 있다
#역행렬을 사용하면 행렬의 방정식을 풀 수 있음
#단위행렬(E): 행-열 수 같음. 오른쪽 아래로 대각선 요소가 1, 그 외 모두 0
#단위행렬은 같은 크기의 행렬에 곱해도 곱하는 대상의 행렬을 변화시키지 않는 성질이 있음
#Numpy의 eye()함수로 표현 가능

import numpy as np

a = np.eye(2) # 2*2단위 행렬
print(a)
print()

a = np.eye(3) # 3*3단위 행렬
print(a)
print()

a = np.eye(4) # 4*4단위 행렬
print(a)


[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#역행렬 : 어떤 행렬에 곱했을 때 단위행렬을 만드는 행렬
#행렬식에 따라 역행렬이 존재하지 않을 수도 있음. 역행렬이 존재할지 여부는 행렬식에 의해 판정할 수 있음
#행렬식의 구현
import numpy as np
a = np.array([[1,2],
              [3,4]])
print(np.linalg.det(a)) #행렬식이 0이 되지 않는 경우

b = np.array([[1,2],
              [0,0]]) 
print(np.linalg.det(b)) #행렬식이 0이 되는 경우

-2.0000000000000004
0.0


In [38]:
#역행렬의 구현
#linalg.inv() 함수를 사용해서 역행렬을 구한다

import numpy as np
a = np.array([[1,2],
              [3,4]])
print(np.linalg.inv(a)) #역행렬

b = np.array([[1,2],
              [0,0]]) 
#print(np.linalg.inv(b)) #역행렬이 존재하지 않으므로 에러가 남

[[-2.   1. ]
 [ 1.5 -0.5]]


In [40]:
#행 수, 열 수가 많은 정방행렬은 역행렬을 손으로 계산할 때, 가우스 소거법, 여인수법 등을 이용하는데
#계산이 조금 복잡해짐.이러한 경우에도 NumPy의 linalg.inv()함수를 사용하면 간단하게 역행렬을 구할 수 있음
#역행렬 -> 인공지능에서 변수끼리 상관관계를 알아보는 회귀 분석에 사용됨

#Question 행렬a의 행렬식을 구하고, 역행렬이 존재하는 경우는 역행렬을 구한다
import numpy as np
a = np.array([[1,1],
              [1,2]])

#행렬식
print(np.linalg.det(a))

#역행렬
print(np.linalg.inv(a))

1.0
[[ 2. -1.]
 [-1.  1.]]
